//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lin.BGA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BGAEntities : DbContext
    {
        public BGAEntities()
            : base("name=BGAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppVersionInfo> AppVersionInfo { get; set; }
        public virtual DbSet<CategoryInfo> CategoryInfo { get; set; }
        public virtual DbSet<MusicInfo> MusicInfo { get; set; }
        public virtual DbSet<StoreInfo> StoreInfo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ProfilesInfo> ProfilesInfo { get; set; }
        public virtual DbSet<MusicLogInfo> MusicLogInfo { get; set; }
    }
}
