//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lin.BGA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryInfo()
        {
            this.MusicInfo = new HashSet<MusicInfo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int SortID { get; set; }
        public bool Enable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicInfo> MusicInfo { get; set; }
    }
}
