//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lin.BGA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicLogInfo
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public string MusicName { get; set; }
        public string CategoryName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime FinishConfirmTime { get; set; }
    
        public virtual StoreInfo StoreInfo { get; set; }
    }
}
